version: "3.7"
services:
  postgres:
    image: postgres:12.19-alpine3.20
    container_name: clinica-database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=clinica-test-db
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
